### ISSUE TITLE
Python 3.7 update breaks installation

### ISSUE THREAD

**Issue by ethansimmons** [fishtown-analytics/homebrew-dbt#1]
OS: macOS High Sierra 10.13.6

After a successful install using `brew install dbt`. I'm getting 
```
$ dbt
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/dbt/0.10.1/libexec/bin/python3.6
  Reason: image not found
Abort trap: 6
```

Looking at installed packages I see that python version `3.7.0` was installed when I installed dbt.
```
$ brew list --versions
dbt 0.10.1
...
git 2.16.2
...
python 3.7.0
python@2 2.7.15_1
...
```

**Comment by ethansimmons** [comment]
To resolve I was able to install [Python 3.6.6](https://www.python.org/downloads/release/python-366/) and copy those files over to my Homebrew python folder. 
Example: `cp -a /Library/Frameworks/Python.framework/Versions/3.6/ /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/`

**Comment by cmcarthur** [comment]
hey @ethansimmons , thanks for writing in about this. i'm taking a look now. glad to hear you found a workaround for the moment.

**Comment by robdimarco** [comment]
Hey @cmcarthur I am having a different issue with Python 3.7. I am doing a `brew install python dbt`. Python 3.7 installs fine, but DBT blows up trying to install PyYAML. 

You can see the full installation log and the `pip` debug file at https://gist.github.com/robdimarco/d804cbb326124a7d0a3fdafd05a087b3

**Comment by cmcarthur** [comment]
@ethansimmons i pushed a workaround for this that installs dbt in a virtualenv with python 2.7 instead of 3.7. can you try to `brew reinstall dbt` and let me know what happens?

**Comment by cmcarthur** [comment]
hey @robdimarco -- try the workaround i posted above (`brew update`, `brew reinstall dbt`) and let me know what happens.

**Comment by ethansimmons** [comment]
Hey @cmcarthur this is what I get when I try to reinstall 😟: 
```
$ brew reinstall dbt
==> Reinstalling fishtown-analytics/dbt/dbt
==> Downloading https://files.pythonhosted.org/packages/5b/ba/67467678992aba725793c703fafd9e3f6cce6ae99c27b4f90ea006dad1d4/dbt-0.10.1.t
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/33/bc/fa0b5347139cd9564f0d44ebd2b147ac97c36b2403943dbee8a25fd74012/virtualenv-1
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dbt--homebrew-virtualenv-20180711-43466-17lmlml/target -
==> python -s /private/tmp/dbt--homebrew-virtualenv-20180711-43466-17lmlml/target/bin/virtualenv -p python /usr/local/Cellar/dbt/0.10.1
Last 15 lines from /Users/ethan.simmons/Library/Logs/Homebrew/dbt/02.python:
2018-07-11 09:30:13 -0500

python
-s
/private/tmp/dbt--homebrew-virtualenv-20180711-43466-17lmlml/target/bin/virtualenv
-p
python
/usr/local/Cellar/dbt/0.10.1/libexec

Traceback (most recent call last):
  File "/private/tmp/dbt--homebrew-virtualenv-20180711-43466-17lmlml/target/bin/virtualenv", line 6, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/fishtown-analytics/homebrew-dbt/issues


Error: Your Xcode (9.2) is outdated.
Please update to Xcode 9.4 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by robdimarco** [comment]
@cmcarthur Tried that and got a new breakage installing cryptography

Full log at
https://gist.github.com/robdimarco/8743877fe4d04d5482732caa32abc88c

**Comment by cmcarthur** [comment]
@robdimarco what version of mac os are you using?

**Comment by cmcarthur** [comment]
@ethansimmons you'll have to upgrade xcode -- unfortunately there isn't a pre-built version of dbt you can use.

sorry for the unpleasantness! we already have a fix for this in the next version of dbt, and we'll release a new patched version of dbt 0.9 with the fix as well after we're done testing.

**Comment by ethansimmons** [comment]
@cmcarthur Not a problem, I ended up just installing with `pip` and have things working, just thought reach out to let you know about the issue in case you weren't already aware.

**Comment by robdimarco** [comment]
@cmcarthur OSX El Capitan 10.11.6

**Comment by nyedidikeke** [comment]
@ethansimmons: can you share output of `brew doctor`?

**Comment by isthistechsupport** [comment]
Hi, bumping because I'm having this exact same issue, but now with the 3.7 -> 3.8 Python update on brew. I tried `brew reinstall dbt` and `brew remove dbt && brew install dbt`, but it seems to remember its old 3.7 binding. Error message:

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/dbt/0.17.0_1/libexec/bin/python3.7
  Reason: image not found
Abort trap: 6
```

Thanks!

**Comment by phildegreat** [comment]
Thanks @isthistechsupport. i was just fixing the same issue and now use pip install instead of homebrew.

**Comment by mgenereu** [comment]
@isthistechsupport The 3.8 stuff is in #5.
